"""empty message

Revision ID: 4f7a77e2c7a0
Revises: 
Create Date: 2019-04-05 14:05:33.323654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7a77e2c7a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports_consultant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PersonID', sa.String(length=191), nullable=True),
    sa.Column('PersonDisplayID', sa.String(length=191), nullable=True),
    sa.Column('PersonType', sa.String(length=191), nullable=True),
    sa.Column('EmailOption', sa.String(length=191), nullable=True),
    sa.Column('Email', sa.String(length=191), nullable=True),
    sa.Column('TaxExempt', sa.String(length=191), nullable=True),
    sa.Column('Gender', sa.String(length=191), nullable=True),
    sa.Column('TranslationLanguage', sa.String(length=191), nullable=True),
    sa.Column('LegalEntityDisplayID', sa.String(length=191), nullable=True),
    sa.Column('DateOfBirth', sa.String(length=191), nullable=True),
    sa.Column('FirstName', sa.String(length=191), nullable=True),
    sa.Column('MiddleName', sa.String(length=191), nullable=True),
    sa.Column('LastName', sa.String(length=191), nullable=True),
    sa.Column('NickName', sa.String(length=191), nullable=True),
    sa.Column('Residential', sa.String(length=191), nullable=True),
    sa.Column('Street1', sa.String(length=191), nullable=True),
    sa.Column('City', sa.String(length=191), nullable=True),
    sa.Column('StateProvince', sa.String(length=191), nullable=True),
    sa.Column('Country', sa.String(length=191), nullable=True),
    sa.Column('PostalCode', sa.String(length=191), nullable=True),
    sa.Column('Region', sa.String(length=191), nullable=True),
    sa.Column('IsValid', sa.String(length=191), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=191), nullable=True),
    sa.Column('PhoneType', sa.String(length=191), nullable=True),
    sa.Column('JoinDate', sa.String(length=191), nullable=True),
    sa.Column('FullName', sa.String(length=191), nullable=True),
    sa.Column('BusinessType', sa.String(length=191), nullable=True),
    sa.Column('ConsultantRank', sa.String(length=191), nullable=True),
    sa.Column('PriceClassification', sa.String(length=191), nullable=True),
    sa.Column('ConsultantType', sa.String(length=191), nullable=True),
    sa.Column('ConsultantStatus', sa.String(length=191), nullable=True),
    sa.Column('ReplicatedSiteURL', sa.String(length=191), nullable=True),
    sa.Column('BlockPortal', sa.String(length=191), nullable=True),
    sa.Column('BlockWebsite', sa.String(length=191), nullable=True),
    sa.Column('ConsultantDisplayID', sa.String(length=191), nullable=True),
    sa.Column('OptOutCompanyEmail', sa.String(length=191), nullable=True),
    sa.Column('OptOutCompanyText', sa.String(length=191), nullable=True),
    sa.Column('OptOutConsultantEmail', sa.String(length=191), nullable=True),
    sa.Column('OptOutConsultantText', sa.String(length=191), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_consultant_BlockPortal'), 'reports_consultant', ['BlockPortal'], unique=False)
    op.create_index(op.f('ix_reports_consultant_BlockWebsite'), 'reports_consultant', ['BlockWebsite'], unique=False)
    op.create_index(op.f('ix_reports_consultant_BusinessType'), 'reports_consultant', ['BusinessType'], unique=False)
    op.create_index(op.f('ix_reports_consultant_City'), 'reports_consultant', ['City'], unique=False)
    op.create_index(op.f('ix_reports_consultant_ConsultantDisplayID'), 'reports_consultant', ['ConsultantDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_consultant_ConsultantRank'), 'reports_consultant', ['ConsultantRank'], unique=False)
    op.create_index(op.f('ix_reports_consultant_ConsultantStatus'), 'reports_consultant', ['ConsultantStatus'], unique=False)
    op.create_index(op.f('ix_reports_consultant_ConsultantType'), 'reports_consultant', ['ConsultantType'], unique=False)
    op.create_index(op.f('ix_reports_consultant_Country'), 'reports_consultant', ['Country'], unique=False)
    op.create_index(op.f('ix_reports_consultant_DateOfBirth'), 'reports_consultant', ['DateOfBirth'], unique=False)
    op.create_index(op.f('ix_reports_consultant_Email'), 'reports_consultant', ['Email'], unique=False)
    op.create_index(op.f('ix_reports_consultant_EmailOption'), 'reports_consultant', ['EmailOption'], unique=False)
    op.create_index(op.f('ix_reports_consultant_FirstName'), 'reports_consultant', ['FirstName'], unique=False)
    op.create_index(op.f('ix_reports_consultant_FullName'), 'reports_consultant', ['FullName'], unique=False)
    op.create_index(op.f('ix_reports_consultant_Gender'), 'reports_consultant', ['Gender'], unique=False)
    op.create_index(op.f('ix_reports_consultant_IsValid'), 'reports_consultant', ['IsValid'], unique=False)
    op.create_index(op.f('ix_reports_consultant_JoinDate'), 'reports_consultant', ['JoinDate'], unique=False)
    op.create_index(op.f('ix_reports_consultant_LastName'), 'reports_consultant', ['LastName'], unique=False)
    op.create_index(op.f('ix_reports_consultant_LegalEntityDisplayID'), 'reports_consultant', ['LegalEntityDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_consultant_MiddleName'), 'reports_consultant', ['MiddleName'], unique=False)
    op.create_index(op.f('ix_reports_consultant_NickName'), 'reports_consultant', ['NickName'], unique=False)
    op.create_index(op.f('ix_reports_consultant_OptOutCompanyEmail'), 'reports_consultant', ['OptOutCompanyEmail'], unique=False)
    op.create_index(op.f('ix_reports_consultant_OptOutCompanyText'), 'reports_consultant', ['OptOutCompanyText'], unique=False)
    op.create_index(op.f('ix_reports_consultant_OptOutConsultantEmail'), 'reports_consultant', ['OptOutConsultantEmail'], unique=False)
    op.create_index(op.f('ix_reports_consultant_OptOutConsultantText'), 'reports_consultant', ['OptOutConsultantText'], unique=False)
    op.create_index(op.f('ix_reports_consultant_PersonDisplayID'), 'reports_consultant', ['PersonDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_consultant_PersonID'), 'reports_consultant', ['PersonID'], unique=False)
    op.create_index(op.f('ix_reports_consultant_PersonType'), 'reports_consultant', ['PersonType'], unique=False)
    op.create_index(op.f('ix_reports_consultant_PhoneNumber'), 'reports_consultant', ['PhoneNumber'], unique=False)
    op.create_index(op.f('ix_reports_consultant_PhoneType'), 'reports_consultant', ['PhoneType'], unique=False)
    op.create_index(op.f('ix_reports_consultant_PostalCode'), 'reports_consultant', ['PostalCode'], unique=False)
    op.create_index(op.f('ix_reports_consultant_PriceClassification'), 'reports_consultant', ['PriceClassification'], unique=False)
    op.create_index(op.f('ix_reports_consultant_Region'), 'reports_consultant', ['Region'], unique=False)
    op.create_index(op.f('ix_reports_consultant_ReplicatedSiteURL'), 'reports_consultant', ['ReplicatedSiteURL'], unique=False)
    op.create_index(op.f('ix_reports_consultant_Residential'), 'reports_consultant', ['Residential'], unique=False)
    op.create_index(op.f('ix_reports_consultant_StateProvince'), 'reports_consultant', ['StateProvince'], unique=False)
    op.create_index(op.f('ix_reports_consultant_Street1'), 'reports_consultant', ['Street1'], unique=False)
    op.create_index(op.f('ix_reports_consultant_TaxExempt'), 'reports_consultant', ['TaxExempt'], unique=False)
    op.create_index(op.f('ix_reports_consultant_TranslationLanguage'), 'reports_consultant', ['TranslationLanguage'], unique=False)
    op.create_table('reports_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.String(length=191), nullable=True),
    sa.Column('OrderDisplayID', sa.String(length=191), nullable=True),
    sa.Column('ConsultantDisplayID', sa.String(length=191), nullable=True),
    sa.Column('PersonDisplayID', sa.String(length=191), nullable=True),
    sa.Column('PersonType', sa.String(length=191), nullable=True),
    sa.Column('LegalEntityDisplayID', sa.String(length=191), nullable=True),
    sa.Column('Email', sa.String(length=191), nullable=True),
    sa.Column('FirstName', sa.String(length=191), nullable=True),
    sa.Column('LastName', sa.String(length=191), nullable=True),
    sa.Column('ShipHold', sa.String(length=191), nullable=True),
    sa.Column('Residential', sa.String(length=191), nullable=True),
    sa.Column('IsValid', sa.String(length=191), nullable=True),
    sa.Column('EventDisplayID', sa.String(length=191), nullable=True),
    sa.Column('OrderDate', sa.String(length=191), nullable=True),
    sa.Column('OrderTotal', sa.String(length=191), nullable=True),
    sa.Column('Subtotal', sa.String(length=191), nullable=True),
    sa.Column('NetSubtotal', sa.String(length=191), nullable=True),
    sa.Column('ShippingTotal', sa.String(length=191), nullable=True),
    sa.Column('HandlingTotal', sa.String(length=191), nullable=True),
    sa.Column('TaxTotal', sa.String(length=191), nullable=True),
    sa.Column('TaxableTotal', sa.String(length=191), nullable=True),
    sa.Column('DiscountTotal', sa.String(length=191), nullable=True),
    sa.Column('ShoppingCart', sa.String(length=191), nullable=True),
    sa.Column('OrderStatus', sa.String(length=191), nullable=True),
    sa.Column('OrderPaymentStatus', sa.String(length=191), nullable=True),
    sa.Column('Locked', sa.String(length=191), nullable=True),
    sa.Column('Commissionable', sa.String(length=191), nullable=True),
    sa.Column('CurrencyTypeAbbreviation', sa.String(length=191), nullable=True),
    sa.Column('CurrencyType', sa.String(length=191), nullable=True),
    sa.Column('CommissionDate', sa.String(length=191), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_order_CommissionDate'), 'reports_order', ['CommissionDate'], unique=False)
    op.create_index(op.f('ix_reports_order_Commissionable'), 'reports_order', ['Commissionable'], unique=False)
    op.create_index(op.f('ix_reports_order_ConsultantDisplayID'), 'reports_order', ['ConsultantDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_order_CurrencyType'), 'reports_order', ['CurrencyType'], unique=False)
    op.create_index(op.f('ix_reports_order_CurrencyTypeAbbreviation'), 'reports_order', ['CurrencyTypeAbbreviation'], unique=False)
    op.create_index(op.f('ix_reports_order_DiscountTotal'), 'reports_order', ['DiscountTotal'], unique=False)
    op.create_index(op.f('ix_reports_order_Email'), 'reports_order', ['Email'], unique=False)
    op.create_index(op.f('ix_reports_order_EventDisplayID'), 'reports_order', ['EventDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_order_FirstName'), 'reports_order', ['FirstName'], unique=False)
    op.create_index(op.f('ix_reports_order_HandlingTotal'), 'reports_order', ['HandlingTotal'], unique=False)
    op.create_index(op.f('ix_reports_order_IsValid'), 'reports_order', ['IsValid'], unique=False)
    op.create_index(op.f('ix_reports_order_LastName'), 'reports_order', ['LastName'], unique=False)
    op.create_index(op.f('ix_reports_order_LegalEntityDisplayID'), 'reports_order', ['LegalEntityDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_order_Locked'), 'reports_order', ['Locked'], unique=False)
    op.create_index(op.f('ix_reports_order_NetSubtotal'), 'reports_order', ['NetSubtotal'], unique=False)
    op.create_index(op.f('ix_reports_order_OrderDate'), 'reports_order', ['OrderDate'], unique=False)
    op.create_index(op.f('ix_reports_order_OrderDisplayID'), 'reports_order', ['OrderDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_order_OrderID'), 'reports_order', ['OrderID'], unique=False)
    op.create_index(op.f('ix_reports_order_OrderPaymentStatus'), 'reports_order', ['OrderPaymentStatus'], unique=False)
    op.create_index(op.f('ix_reports_order_OrderStatus'), 'reports_order', ['OrderStatus'], unique=False)
    op.create_index(op.f('ix_reports_order_OrderTotal'), 'reports_order', ['OrderTotal'], unique=False)
    op.create_index(op.f('ix_reports_order_PersonDisplayID'), 'reports_order', ['PersonDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_order_PersonType'), 'reports_order', ['PersonType'], unique=False)
    op.create_index(op.f('ix_reports_order_Residential'), 'reports_order', ['Residential'], unique=False)
    op.create_index(op.f('ix_reports_order_ShipHold'), 'reports_order', ['ShipHold'], unique=False)
    op.create_index(op.f('ix_reports_order_ShippingTotal'), 'reports_order', ['ShippingTotal'], unique=False)
    op.create_index(op.f('ix_reports_order_ShoppingCart'), 'reports_order', ['ShoppingCart'], unique=False)
    op.create_index(op.f('ix_reports_order_Subtotal'), 'reports_order', ['Subtotal'], unique=False)
    op.create_index(op.f('ix_reports_order_TaxTotal'), 'reports_order', ['TaxTotal'], unique=False)
    op.create_index(op.f('ix_reports_order_TaxableTotal'), 'reports_order', ['TaxableTotal'], unique=False)
    op.create_table('reports_order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('OrderID', sa.String(length=191), nullable=True),
    sa.Column('OrderDisplayID', sa.String(length=191), nullable=True),
    sa.Column('OrderLineID', sa.String(length=191), nullable=True),
    sa.Column('SequenceNumber', sa.String(length=191), nullable=True),
    sa.Column('OrderLineStatus', sa.String(length=191), nullable=True),
    sa.Column('Price', sa.String(length=191), nullable=True),
    sa.Column('WarehouseBinDisplayID', sa.String(length=191), nullable=True),
    sa.Column('WarehouseDisplayID', sa.String(length=191), nullable=True),
    sa.Column('TaxableAmount', sa.String(length=191), nullable=True),
    sa.Column('Tax', sa.String(length=191), nullable=True),
    sa.Column('Quantity', sa.String(length=191), nullable=True),
    sa.Column('ShippingPrice', sa.String(length=191), nullable=True),
    sa.Column('HandlingPrice', sa.String(length=191), nullable=True),
    sa.Column('Discounts', sa.String(length=191), nullable=True),
    sa.Column('Subtotal', sa.String(length=191), nullable=True),
    sa.Column('NetSubtotal', sa.String(length=191), nullable=True),
    sa.Column('LineTotal', sa.String(length=191), nullable=True),
    sa.Column('ProductID', sa.String(length=191), nullable=True),
    sa.Column('SKU', sa.String(length=191), nullable=True),
    sa.Column('QuantityInvoiced', sa.String(length=191), nullable=True),
    sa.Column('QuantityShipped', sa.String(length=191), nullable=True),
    sa.Column('QuantityShippedAndClosed', sa.String(length=191), nullable=True),
    sa.Column('QuantityBackOrdered', sa.String(length=191), nullable=True),
    sa.Column('UnitWeight', sa.String(length=191), nullable=True),
    sa.Column('VirtualProduct', sa.String(length=191), nullable=True),
    sa.Column('ChargeShipping', sa.String(length=191), nullable=True),
    sa.Column('ChargeHandling', sa.String(length=191), nullable=True),
    sa.Column('ProductTaxCode', sa.String(length=191), nullable=True),
    sa.Column('ConsultantDisplayID', sa.String(length=191), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_order_line_ChargeHandling'), 'reports_order_line', ['ChargeHandling'], unique=False)
    op.create_index(op.f('ix_reports_order_line_ChargeShipping'), 'reports_order_line', ['ChargeShipping'], unique=False)
    op.create_index(op.f('ix_reports_order_line_ConsultantDisplayID'), 'reports_order_line', ['ConsultantDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_order_line_Discounts'), 'reports_order_line', ['Discounts'], unique=False)
    op.create_index(op.f('ix_reports_order_line_HandlingPrice'), 'reports_order_line', ['HandlingPrice'], unique=False)
    op.create_index(op.f('ix_reports_order_line_LineTotal'), 'reports_order_line', ['LineTotal'], unique=False)
    op.create_index(op.f('ix_reports_order_line_NetSubtotal'), 'reports_order_line', ['NetSubtotal'], unique=False)
    op.create_index(op.f('ix_reports_order_line_OrderDisplayID'), 'reports_order_line', ['OrderDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_order_line_OrderID'), 'reports_order_line', ['OrderID'], unique=False)
    op.create_index(op.f('ix_reports_order_line_OrderLineID'), 'reports_order_line', ['OrderLineID'], unique=False)
    op.create_index(op.f('ix_reports_order_line_OrderLineStatus'), 'reports_order_line', ['OrderLineStatus'], unique=False)
    op.create_index(op.f('ix_reports_order_line_Price'), 'reports_order_line', ['Price'], unique=False)
    op.create_index(op.f('ix_reports_order_line_ProductID'), 'reports_order_line', ['ProductID'], unique=False)
    op.create_index(op.f('ix_reports_order_line_ProductTaxCode'), 'reports_order_line', ['ProductTaxCode'], unique=False)
    op.create_index(op.f('ix_reports_order_line_Quantity'), 'reports_order_line', ['Quantity'], unique=False)
    op.create_index(op.f('ix_reports_order_line_QuantityBackOrdered'), 'reports_order_line', ['QuantityBackOrdered'], unique=False)
    op.create_index(op.f('ix_reports_order_line_QuantityInvoiced'), 'reports_order_line', ['QuantityInvoiced'], unique=False)
    op.create_index(op.f('ix_reports_order_line_QuantityShipped'), 'reports_order_line', ['QuantityShipped'], unique=False)
    op.create_index(op.f('ix_reports_order_line_QuantityShippedAndClosed'), 'reports_order_line', ['QuantityShippedAndClosed'], unique=False)
    op.create_index(op.f('ix_reports_order_line_SKU'), 'reports_order_line', ['SKU'], unique=False)
    op.create_index(op.f('ix_reports_order_line_SequenceNumber'), 'reports_order_line', ['SequenceNumber'], unique=False)
    op.create_index(op.f('ix_reports_order_line_ShippingPrice'), 'reports_order_line', ['ShippingPrice'], unique=False)
    op.create_index(op.f('ix_reports_order_line_Subtotal'), 'reports_order_line', ['Subtotal'], unique=False)
    op.create_index(op.f('ix_reports_order_line_Tax'), 'reports_order_line', ['Tax'], unique=False)
    op.create_index(op.f('ix_reports_order_line_TaxableAmount'), 'reports_order_line', ['TaxableAmount'], unique=False)
    op.create_index(op.f('ix_reports_order_line_UnitWeight'), 'reports_order_line', ['UnitWeight'], unique=False)
    op.create_index(op.f('ix_reports_order_line_VirtualProduct'), 'reports_order_line', ['VirtualProduct'], unique=False)
    op.create_index(op.f('ix_reports_order_line_WarehouseBinDisplayID'), 'reports_order_line', ['WarehouseBinDisplayID'], unique=False)
    op.create_index(op.f('ix_reports_order_line_WarehouseDisplayID'), 'reports_order_line', ['WarehouseDisplayID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_order_line_WarehouseDisplayID'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_WarehouseBinDisplayID'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_VirtualProduct'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_UnitWeight'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_TaxableAmount'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_Tax'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_Subtotal'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_ShippingPrice'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_SequenceNumber'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_SKU'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_QuantityShippedAndClosed'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_QuantityShipped'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_QuantityInvoiced'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_QuantityBackOrdered'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_Quantity'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_ProductTaxCode'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_ProductID'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_Price'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_OrderLineStatus'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_OrderLineID'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_OrderID'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_OrderDisplayID'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_NetSubtotal'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_LineTotal'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_HandlingPrice'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_Discounts'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_ConsultantDisplayID'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_ChargeShipping'), table_name='reports_order_line')
    op.drop_index(op.f('ix_reports_order_line_ChargeHandling'), table_name='reports_order_line')
    op.drop_table('reports_order_line')
    op.drop_index(op.f('ix_reports_order_TaxableTotal'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_TaxTotal'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_Subtotal'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_ShoppingCart'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_ShippingTotal'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_ShipHold'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_Residential'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_PersonType'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_PersonDisplayID'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_OrderTotal'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_OrderStatus'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_OrderPaymentStatus'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_OrderID'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_OrderDisplayID'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_OrderDate'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_NetSubtotal'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_Locked'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_LegalEntityDisplayID'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_LastName'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_IsValid'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_HandlingTotal'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_FirstName'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_EventDisplayID'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_Email'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_DiscountTotal'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_CurrencyTypeAbbreviation'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_CurrencyType'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_ConsultantDisplayID'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_Commissionable'), table_name='reports_order')
    op.drop_index(op.f('ix_reports_order_CommissionDate'), table_name='reports_order')
    op.drop_table('reports_order')
    op.drop_index(op.f('ix_reports_consultant_TranslationLanguage'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_TaxExempt'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_Street1'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_StateProvince'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_Residential'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_ReplicatedSiteURL'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_Region'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_PriceClassification'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_PostalCode'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_PhoneType'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_PhoneNumber'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_PersonType'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_PersonID'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_PersonDisplayID'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_OptOutConsultantText'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_OptOutConsultantEmail'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_OptOutCompanyText'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_OptOutCompanyEmail'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_NickName'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_MiddleName'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_LegalEntityDisplayID'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_LastName'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_JoinDate'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_IsValid'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_Gender'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_FullName'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_FirstName'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_EmailOption'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_Email'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_DateOfBirth'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_Country'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_ConsultantType'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_ConsultantStatus'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_ConsultantRank'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_ConsultantDisplayID'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_City'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_BusinessType'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_BlockWebsite'), table_name='reports_consultant')
    op.drop_index(op.f('ix_reports_consultant_BlockPortal'), table_name='reports_consultant')
    op.drop_table('reports_consultant')
    # ### end Alembic commands ###
